Only play the long 'Waking Up' explanation five times
MycroftAI/skill-naptime pull request #25
Opened 2019-01-22 10:26 UTC by StefanBCN

The default message when Mycroft is going to sleep takes quite a while to complete, which is frustrating when you're trying to get Mycroft to be quiet when you're watching TV or having a conversation. This change tweaks it so after the fifth time Mycroft has explained about waking up he'll just say "Okay" when you tell him to go to sleep.

2019-01-22 10:34 UTC, forslund requested changes
I've added a bunch of comments. Hope you don't think they're unreasonable.

2019-01-22 10:34 UTC, forslund commented on __init__.py
> +            count += 1
Above can be simplified by setting the default value to 0:
```python
        count = self.settings.get('Wake up explanation count', 0)
        count += 1
```

2019-01-22 10:34 UTC, forslund commented on __init__.py
> +            self.speak_dialog('going.to.sleep.short', dict(wake_word=self.wake_word))
This doesn't need the dict(...) part

2019-01-22 10:34 UTC, forslund commented on __init__.py
> +        count = self.settings.get('Wake up explanation count')
Maybe we could shorten 'Wake up explanation count' value to 'wake up count'

2019-01-22 10:34 UTC, forslund commented on dialog/en-us/going.to.sleep.short.dialog
> +Okay.
Maybe add a second line as an alternative with just: `Going to sleep` slightly longer but not by much. (You don't need to translate it to the other languages if that's hard, that will be picked up on translate.mycroft.ai)

2019-01-22 10:39 UTC, StefanBCN commented
Thanks for the input, changes are going up now

2019-01-22 10:53 UTC, forslund commented
Looks pretty good now thanks!

Before I can include this change we need you to sign our [Contributor License Agreement](https://mycroft.ai/cla). This is a formality to protect yourself, Mycroft AI and our community. This agreement makes it crystal clear that along with your code you are offering a license to use it within the confines of this project. You retain ownership of the code, this is just a license.

This is a one time thing for your future contributions this step won't be needed.

2019-01-22 10:54 UTC, StefanBCN commented
Done :+1:

2019-01-22 10:56 UTC, forslund commented
Thank you, once it's registered I should be able to merge this.

2019-01-22 13:24 UTC, forslund approved these changes

2019-02-21 08:10 UTC, forslund commented
Hi @StefanBCN, I've merged this into the 19.02 branch via #27. Thanks for the contribution!

2019-02-21 08:10 UTC, closed without merging